import { Suspense } from "react";
import localFont from "next/font/local";
import "./globals.css";
import ProductsProvider from "@/contexts/ProductsContext";
import CategoriesProvider from "@/contexts/CategoriesContext";
import CartProvider from "@/contexts/CartContext";
import CheckoutProvider from "@/contexts/CheckouContext";
import { NuqsAdapter } from "nuqs/adapters/next/app";

// import {Playfair_Display} from "next/font/google/index"

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });
// const serif = Playfair_Display({
//   subsets: ['latin'],
//   variable: "--font-playfair",
//   weight: ["400", "700"],
//   display: "swap"
// });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="antialiased">
        <Suspense fallback={<div>Loading...</div>}>
          <NuqsAdapter>
            <div className="flex gap-5">
              <CategoriesProvider>
                <ProductsProvider>
                  <CartProvider>
                    <CheckoutProvider>{children}</CheckoutProvider>
                  </CartProvider>
                </ProductsProvider>
              </CategoriesProvider>
            </div>
          </NuqsAdapter>
        </Suspense>
      </body>
    </html>
  );
}
