import { Suspense } from "react";
import localFont from "next/font/local";
import { Playfair_Display, Inter } from "next/font/google";
import "./globals.css";
import ProductsProvider from "@/contexts/ProductsContext";
import CategoriesProvider from "@/contexts/CategoriesContext";
import CartProvider from "@/contexts/CartContext";
import CheckoutProvider from "@/contexts/CheckouContext";
import { NuqsAdapter } from "nuqs/adapters/next/app";

// Define your fonts
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

const playfair = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-playfair",
  weight: ["400", "700"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`antialiased bg-background text-foreground ${inter.variable} ${playfair.variable} w-screen`}
      >
        <Suspense fallback={<div>Loading...</div>}>
          <NuqsAdapter>
            <CategoriesProvider>
              <ProductsProvider>
                <CartProvider>
                  <CheckoutProvider>{children}</CheckoutProvider>
                </CartProvider>
              </ProductsProvider>
            </CategoriesProvider>
          </NuqsAdapter>
        </Suspense>
      </body>
    </html>
  );
}
